### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by Austyns** [cherepets/SimpleAppx#1]
Very interesting project but please, How do i use

**Comment by cherepets** [comment]
It's quite simple: first you need to get .appxrecipe from Visual Studio.
Now you can right click on it -> "Open with" -> SimpleAppx.
Alternatively you can pass multiple filenames to it via console (just take a look here: https://github.com/cherepets/SimpleAppx/blob/master/Program.cs#L17 )

**Comment by Austyns** [comment]
Thanks a lot. It works well. Thank you
